/**
 * @fileoverview gRPC-Web generated client stub for service2
 * @enhanceable
 * @public
 */

// Code generated by protoc-gen-grpc-web. DO NOT EDIT.
// versions:
// 	protoc-gen-grpc-web v1.4.2
// 	protoc              v4.22.0
// source: service2.proto


/* eslint-disable */
// @ts-nocheck



const grpc = {};
grpc.web = require('grpc-web');

const proto = {};
proto.service2 = require('./service2_pb.js');

/**
 * @param {string} hostname
 * @param {?Object} credentials
 * @param {?grpc.web.ClientOptions} options
 * @constructor
 * @struct
 * @final
 */
proto.service2.PingPong2Client =
    function(hostname, credentials, options) {
  if (!options) options = {};
  options.format = 'text';

  /**
   * @private @const {!grpc.web.GrpcWebClientBase} The client
   */
  this.client_ = new grpc.web.GrpcWebClientBase(options);

  /**
   * @private @const {string} The hostname
   */
  this.hostname_ = hostname.replace(/\/+$/, '');

};


/**
 * @param {string} hostname
 * @param {?Object} credentials
 * @param {?grpc.web.ClientOptions} options
 * @constructor
 * @struct
 * @final
 */
proto.service2.PingPong2PromiseClient =
    function(hostname, credentials, options) {
  if (!options) options = {};
  options.format = 'text';

  /**
   * @private @const {!grpc.web.GrpcWebClientBase} The client
   */
  this.client_ = new grpc.web.GrpcWebClientBase(options);

  /**
   * @private @const {string} The hostname
   */
  this.hostname_ = hostname.replace(/\/+$/, '');

};


/**
 * @const
 * @type {!grpc.web.MethodDescriptor<
 *   !proto.service2.Ping2Request,
 *   !proto.service2.Pong2Response>}
 */
const methodDescriptor_PingPong2_Ping2 = new grpc.web.MethodDescriptor(
  '/service2.PingPong2/Ping2',
  grpc.web.MethodType.UNARY,
  proto.service2.Ping2Request,
  proto.service2.Pong2Response,
  /**
   * @param {!proto.service2.Ping2Request} request
   * @return {!Uint8Array}
   */
  function(request) {
    return request.serializeBinary();
  },
  proto.service2.Pong2Response.deserializeBinary
);


/**
 * @param {!proto.service2.Ping2Request} request The
 *     request proto
 * @param {?Object<string, string>} metadata User defined
 *     call metadata
 * @param {function(?grpc.web.RpcError, ?proto.service2.Pong2Response)}
 *     callback The callback function(error, response)
 * @return {!grpc.web.ClientReadableStream<!proto.service2.Pong2Response>|undefined}
 *     The XHR Node Readable Stream
 */
proto.service2.PingPong2Client.prototype.ping2 =
    function(request, metadata, callback) {
  return this.client_.rpcCall(this.hostname_ +
      '/service2.PingPong2/Ping2',
      request,
      metadata || {},
      methodDescriptor_PingPong2_Ping2,
      callback);
};


/**
 * @param {!proto.service2.Ping2Request} request The
 *     request proto
 * @param {?Object<string, string>=} metadata User defined
 *     call metadata
 * @return {!Promise<!proto.service2.Pong2Response>}
 *     Promise that resolves to the response
 */
proto.service2.PingPong2PromiseClient.prototype.ping2 =
    function(request, metadata) {
  return this.client_.unaryCall(this.hostname_ +
      '/service2.PingPong2/Ping2',
      request,
      metadata || {},
      methodDescriptor_PingPong2_Ping2);
};


module.exports = proto.service2;

